//! # TypeScript Type Export Tests
//!
//! This module exports all TypeScript types to the frontend when run with
//! the `typescript` feature enabled.
//!
//! ## Usage
//!
//! ```bash
//! cargo test -p ckrv-transport --features typescript export_typescript_types -- --ignored
//! ```
//!
//! The types are exported to `crates/ckrv-ui/frontend/src/types/api.generated.ts`.

#[cfg(feature = "typescript")]
mod export {
    use std::fs;
    use std::path::PathBuf;

    /// Get the output path for generated TypeScript types.
    fn get_output_path() -> PathBuf {
        let manifest_dir = env!("CARGO_MANIFEST_DIR");
        PathBuf::from(manifest_dir)
            .parent()
            .unwrap()
            .join("ckrv-ui/frontend/src/types/api.generated.ts")
    }

    /// Convert ts-rs decl output to exported type.
    fn export_type(decl: &str) -> String {
        decl.replace("type ", "export type ")
    }

    /// Export all TypeScript types to a single file.
    ///
    /// This test is marked as `#[ignore]` so it only runs when explicitly called.
    /// Run with: `cargo test --features typescript export_typescript_types -- --ignored`
    #[test]
    #[ignore]
    fn export_typescript_types() {
        use ts_rs::TS;

        let output_path = get_output_path();

        // Ensure the directory exists
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent).expect("Failed to create output directory");
        }

        let mut output = String::new();
        output.push_str("// =============================================================\n");
        output.push_str("// AUTO-GENERATED FILE - DO NOT EDIT\n");
        output.push_str("// =============================================================\n");
        output.push_str("// Generated by: cargo test -p ckrv-transport --features typescript export_typescript_types -- --ignored\n");
        output.push_str(&format!(
            "// Generated at: {}\n",
            chrono::Utc::now().to_rfc3339()
        ));
        output.push_str("// =============================================================\n\n");

        // Add JsonValue type for serde_json::Value compatibility
        output.push_str("// eslint-disable-next-line @typescript-eslint/no-explicit-any\n");
        output.push_str("export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };\n\n");

        // Common types
        output.push_str("// === Common Types ===\n\n");
        output.push_str(&export_type(&ckrv_transport::DockerStatus::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::SuccessResponse::decl()));
        output.push_str("\n\n");

        // Agent types
        output.push_str("// === Agent Types ===\n\n");
        output.push_str(&export_type(&ckrv_transport::AgentType::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::AgentConfig::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::AgentSpecificConfig::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::OpenRouterConfig::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::GlmConfig::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::OpenRouterModel::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::UpsertAgentRequest::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::DeleteAgentRequest::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::SetDefaultAgentRequest::decl()));
        output.push_str("\n\n");

        // Spec types
        output.push_str("// === Spec Types ===\n\n");
        output.push_str(&export_type(&ckrv_transport::SpecSummary::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::SpecDetail::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::SpecStatus::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::CreateSpecRequest::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::UpdateSpecRequest::decl()));
        output.push_str("\n\n");

        // Plan types
        output.push_str("// === Plan Types ===\n\n");
        output.push_str(&export_type(&ckrv_transport::PlanSummary::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::PlanDetail::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::BatchSummary::decl()));
        output.push_str("\n\n");

        // Task types
        output.push_str("// === Task Types ===\n\n");
        output.push_str(&export_type(&ckrv_transport::TaskSummary::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::TaskDetail::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::TaskStatus::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::UpdateTaskRequest::decl()));
        output.push_str("\n\n");

        // Execution types
        output.push_str("// === Execution Types ===\n\n");
        output.push_str(&export_type(&ckrv_transport::ExecutionRun::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::ExecutionStatus::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::TaskRun::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::StartExecutionRequest::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::StopExecutionRequest::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::StartExecutionResponse::decl()));
        output.push_str("\n\n");

        // History types
        output.push_str("// === History Types ===\n\n");
        output.push_str(&export_type(&ckrv_transport::RunStatus::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::RunSummary::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::RunDetail::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::BatchRunDetail::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::CreateRunRequest::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::BatchInfo::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::UpdateRunRequest::decl()));
        output.push_str("\n\n");

        // Test/QA types
        output.push_str("// === Test/QA Types ===\n\n");
        output.push_str(&export_type(&ckrv_transport::TestRunRequest::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::TestPlanRequest::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::TestWriteRequest::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::TestResult::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::TestCaseResult::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::TestCaseStatus::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::QaReviewRequest::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::QaBugsRequest::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::QaReportRequest::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::QaReviewResult::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::QaIssue::decl()));
        output.push_str("\n\n");
        output.push_str(&export_type(&ckrv_transport::IssueSeverity::decl()));
        output.push_str("\n\n");

        // Write output
        fs::write(&output_path, output).expect("Failed to write TypeScript types");

        println!("TypeScript types exported to: {}", output_path.display());
    }
}
