// =============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT
// =============================================================================
// Generated by: cargo test -p ckrv-transport --features typescript export_typescript_types -- --ignored
// Generated at: 2026-02-04T14:04:03.243620449+00:00
// =============================================================================

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

// === Common Types ===

export type DockerStatus = {
    /**
     * Whether Docker daemon is running
     */
    available: boolean,
    /**
     * Docker version if available
     */
    version: string | null,
    /**
     * Error message if Docker is not available
     */
    error: string | null,
};

export type SuccessResponse = {
    /**
     * Success message
     */
    message: string,
};

// === Agent Types ===

export type AgentType = "claude" | "claude_open_router" | "claude_glm" | "codex" | "kilo_code" | "gemini" | "cursor" | "amp" | "qwen" | "opencode" | "factory_droid" | "github_copilot" | "mistral_vibe";

export type AgentConfig = {
    /**
     * Unique identifier for this agent
     */
    name: string,
    /**
     * Human-readable display name
     */
    display_name: string,
    /**
     * Agent backend type
     */
    agent_type: AgentType,
    /**
     * Model identifier (e.g., "anthropic/claude-3-opus")
     */
    model: string | null,
    /**
     * Whether this is the default agent
     */
    is_default: boolean,
    /**
     * Whether this agent is enabled
     */
    enabled: boolean,
} & (OpenRouterConfig | GlmConfig | null);

export type AgentSpecificConfig = OpenRouterConfig | GlmConfig | null;

export type OpenRouterConfig = {
    /**
     * Environment variable containing API key
     */
    api_key_env: string,
    /**
     * Model ID on OpenRouter
     */
    model_id: string,
};

export type GlmConfig = {
    /**
     * Environment variable containing API key
     */
    api_key_env: string,
    /**
     * Optional custom endpoint
     */
    endpoint: string | null,
};

export type GeminiConfig = {
    /**
     * Optional model override (e.g., "gemini-2.5-pro")
     */
    model: string | null,
};

export type OpenRouterModel = {
    /**
     * Model ID
     */
    id: string,
    /**
     * Model display name
     */
    name: string,
    /**
     * Model description
     */
    description: string | null,
    /**
     * Context window size
     */
    context_length: number | null,
    /**
     * Pricing per 1M input tokens
     */
    pricing_prompt: string | null,
    /**
     * Pricing per 1M output tokens
     */
    pricing_completion: string | null,
};

export type UpsertAgentRequest = {
    /**
     * Agent configuration to create/update
     */
    agent: AgentConfig,
};

export type DeleteAgentRequest = {
    /**
     * Name of agent to delete
     */
    name: string,
};

export type SetDefaultAgentRequest = {
    /**
     * Name of agent to set as default
     */
    name: string,
};

// === Spec Types ===

export type SpecSummary = {
    /**
     * Spec name (directory name)
     */
    name: string,
    /**
     * Relative path to spec directory
     */
    path: string,
    /**
     * Human-readable title
     */
    title: string | null,
    /**
     * Current status
     */
    status: SpecStatus,
    /**
     * Has execution plan
     */
    has_plan: boolean,
    /**
     * Has tasks
     */
    has_tasks: boolean,
    /**
     * Has design artifact
     */
    has_design: boolean,
    /**
     * Has implementation artifact
     */
    has_implementation: boolean,
    /**
     * Implementation branch name if available
     */
    implementation_branch: string | null,
    /**
     * Number of tasks
     */
    task_count: number,
    /**
     * Created timestamp (ISO 8601)
     */
    created_at: string | null,
    /**
     * Last modified timestamp (ISO 8601)
     */
    updated_at: string | null,
};

export type SpecDetail = {
    /**
     * Spec ID
     */
    id: string,
    /**
     * Overview/goal text
     */
    overview: string | null,
    /**
     * Status string
     */
    status: string | null,
    /**
     * Branch name
     */
    branch: string | null,
    /**
     * Created timestamp
     */
    created: string | null,
    /**
     * User stories
     */
    user_stories: Array<JsonValue>,
    /**
     * Requirements
     */
    requirements: Array<JsonValue>,
    /**
     * Success criteria
     */
    success_criteria: Array<JsonValue>,
    /**
     * Assumptions
     */
    assumptions: Array<string>,
    /**
     * Edge cases
     */
    edge_cases: Array<string>,
    /**
     * Raw YAML content
     */
    raw_yaml: string | null,
};

export type SpecStatus = "draft" | "planned" | "in_progress" | "implemented" | "failed";

export type CreateSpecRequest = {
    /**
     * Description of what to build
     */
    description: string,
    /**
     * Optional name for the spec
     */
    name: string | null,
};

export type UpdateSpecRequest = {
    /**
     * Raw YAML content to save
     */
    raw_yaml: string | null,
};

// === Plan Types ===

export type PlanSummary = {
    /**
     * Spec name this plan belongs to
     */
    spec_name: string,
    /**
     * Number of batches
     */
    batch_count: number,
    /**
     * Total estimated cost
     */
    total_estimated_cost: number | null,
    /**
     * Status
     */
    status: string | null,
};

export type PlanDetail = {
    /**
     * Spec name
     */
    spec_name: string,
    /**
     * Batches in this plan
     */
    batches: Array<BatchSummary>,
    /**
     * Raw YAML content
     */
    raw_yaml: string | null,
};

export type BatchSummary = {
    /**
     * Batch ID
     */
    id: string,
    /**
     * Batch name
     */
    name: string,
    /**
     * Number of tasks
     */
    task_count: number,
    /**
     * Batch status
     */
    status: string,
    /**
     * Estimated cost
     */
    estimated_cost: number | null,
};

// === Task Types ===

export type TaskSummary = {
    /**
     * Task ID
     */
    id: string,
    /**
     * Task title
     */
    title: string,
    /**
     * Current status
     */
    status: TaskStatus,
    /**
     * Complexity (1-5)
     */
    complexity: number,
    /**
     * Phase this task belongs to
     */
    phase: string | null,
};

export type TaskDetail = {
    /**
     * Task ID
     */
    id: string,
    /**
     * Task title
     */
    title: string,
    /**
     * Task description
     */
    description: string | null,
    /**
     * Current status
     */
    status: TaskStatus,
    /**
     * Complexity (1-5)
     */
    complexity: number,
    /**
     * Phase this task belongs to
     */
    phase: string | null,
    /**
     * Target file path
     */
    file_path: string | null,
    /**
     * Related user story
     */
    user_story: string | null,
    /**
     * Can run in parallel
     */
    parallel: boolean,
    /**
     * Model tier
     */
    model_tier: string | null,
    /**
     * Estimated tokens
     */
    estimated_tokens: number | null,
    /**
     * Context files required
     */
    context_required: Array<string> | null,
};

export type TaskStatus = "pending" | "queued" | "running" | "in_progress" | "completed" | "failed" | "skipped";

export type UpdateTaskRequest = {
    /**
     * New status
     */
    status: TaskStatus | null,
};

// === Execution Types ===

export type ExecutionRun = {
    /**
     * Unique run identifier
     */
    id: string,
    /**
     * Spec this run belongs to
     */
    spec: string,
    /**
     * When the run started (ISO 8601)
     */
    started_at: string,
    /**
     * When the run completed (if finished)
     */
    completed_at: string | null,
    /**
     * Current status
     */
    status: ExecutionStatus,
    /**
     * Tasks in this run
     */
    tasks: Array<TaskRun>,
};

export type ExecutionStatus = "pending" | "running" | "completed" | "failed" | "cancelled";

export type TaskRun = {
    /**
     * Task identifier
     */
    id: string,
    /**
     * Task title
     */
    title: string,
    /**
     * Current status
     */
    status: TaskStatus,
    /**
     * Agent assigned to this task
     */
    agent: string | null,
    /**
     * Git worktree path
     */
    worktree: string | null,
    /**
     * Attempt count
     */
    attempts: number,
    /**
     * Error message (if failed)
     */
    error: string | null,
    /**
     * Task output/logs if available
     */
    output: string | null,
};

export type StartExecutionRequest = {
    /**
     * Spec to execute
     */
    spec: string,
    /**
     * Optional agent to use (defaults to system default)
     */
    agent: string | null,
    /**
     * Whether to perform a dry run
     */
    dry_run: boolean | null,
    /**
     * Optional list of specific task IDs to run
     */
    task_ids: Array<string> | null,
};

export type StopExecutionRequest = {
    /**
     * Spec to stop execution for
     */
    spec: string,
};

export type StartExecutionResponse = {
    /**
     * Run identifier
     */
    run_id: string,
    /**
     * Initial status
     */
    status: ExecutionStatus,
};

// === History Types ===

export type RunStatus = "running" | "completed" | "failed" | "aborted";

export type RunSummary = {
    /**
     * Unique run identifier
     */
    id: string,
    /**
     * Spec that was executed
     */
    spec_name: string,
    /**
     * Run status
     */
    status: RunStatus,
    /**
     * When the run started (ISO 8601)
     */
    started_at: string,
    /**
     * When the run completed
     */
    ended_at: string | null,
    /**
     * Number of batches
     */
    batch_count: number,
    /**
     * Completed batches
     */
    completed_batches: number,
};

export type RunDetail = {
    /**
     * Unique run identifier
     */
    id: string,
    /**
     * Spec that was executed
     */
    spec_name: string,
    /**
     * Run status
     */
    status: RunStatus,
    /**
     * When the run started (ISO 8601)
     */
    started_at: string,
    /**
     * When the run completed
     */
    ended_at: string | null,
    /**
     * Was this a dry run
     */
    dry_run: boolean,
    /**
     * Elapsed time in seconds
     */
    elapsed_seconds: bigint | null,
    /**
     * Batches in this run
     */
    batches: Array<BatchRunDetail>,
    /**
     * Error message if failed
     */
    error: string | null,
};

export type BatchRunDetail = {
    /**
     * Batch ID
     */
    id: string,
    /**
     * Batch name
     */
    name: string,
    /**
     * Batch status
     */
    status: string,
    /**
     * When started
     */
    started_at: string | null,
    /**
     * When completed
     */
    ended_at: string | null,
    /**
     * Git branch created
     */
    branch: string | null,
    /**
     * Error message if failed
     */
    error: string | null,
};

export type CreateRunRequest = {
    /**
     * Run ID
     */
    run_id: string,
    /**
     * Dry run mode
     */
    dry_run: boolean,
    /**
     * Batches to include
     */
    batches: Array<BatchInfo>,
};

export type BatchInfo = {
    /**
     * Batch ID
     */
    id: string,
    /**
     * Batch name
     */
    name: string,
};

export type UpdateRunRequest = {
    /**
     * New status
     */
    status: RunStatus | null,
    /**
     * Error message
     */
    error: string | null,
};

// === Test/QA Types ===

export type TestRunRequest = {
    /**
     * Path to test (file, directory, or pattern)
     */
    path: string | null,
    /**
     * Test framework to use
     */
    framework: string | null,
    /**
     * Whether to run in watch mode
     */
    watch: boolean | null,
    /**
     * Filter pattern for tests
     */
    filter: string | null,
};

export type TestPlanRequest = {
    /**
     * Spec to generate test plan for
     */
    spec: string,
    /**
     * Agent to use for planning
     */
    agent: string | null,
};

export type TestWriteRequest = {
    /**
     * Path to generate tests for
     */
    path: string,
    /**
     * Agent to use for writing tests
     */
    agent: string | null,
    /**
     * Test framework to use
     */
    framework: string | null,
};

export type TestResult = {
    /**
     * Whether tests passed
     */
    passed: boolean,
    /**
     * Number of passed tests
     */
    passed_count: number,
    /**
     * Number of failed tests
     */
    failed_count: number,
    /**
     * Number of skipped tests
     */
    skipped_count: number,
    /**
     * Total test duration in milliseconds
     */
    duration_ms: bigint,
    /**
     * Test output/logs
     */
    output: string,
    /**
     * Individual test results
     */
    tests: Array<TestCaseResult>,
};

export type TestCaseResult = {
    /**
     * Test name
     */
    name: string,
    /**
     * Test status
     */
    status: TestCaseStatus,
    /**
     * Duration in milliseconds
     */
    duration_ms: bigint | null,
    /**
     * Error message if failed
     */
    error: string | null,
};

export type TestCaseStatus = "passed" | "failed" | "skipped";

export type QaReviewRequest = {
    /**
     * Path to review
     */
    path: string | null,
    /**
     * Spec to review
     */
    spec: string | null,
    /**
     * Agent to use for review
     */
    agent: string | null,
};

export type QaBugsRequest = {
    /**
     * Path to scan for bugs
     */
    path: string | null,
    /**
     * Agent to use for bug detection
     */
    agent: string | null,
};

export type QaReportRequest = {
    /**
     * Spec to generate report for
     */
    spec: string,
    /**
     * Report format (markdown, html, json)
     */
    format: string | null,
};

export type QaReviewResult = {
    /**
     * Overall quality score (0-100)
     */
    score: number,
    /**
     * Summary of findings
     */
    summary: string,
    /**
     * Detailed issues found
     */
    issues: Array<QaIssue>,
    /**
     * Recommendations
     */
    recommendations: Array<string>,
};

export type QaIssue = {
    /**
     * Issue severity
     */
    severity: IssueSeverity,
    /**
     * Issue category
     */
    category: string,
    /**
     * Issue description
     */
    description: string,
    /**
     * File path if applicable
     */
    file: string | null,
    /**
     * Line number if applicable
     */
    line: number | null,
    /**
     * Suggested fix
     */
    fix: string | null,
};

export type IssueSeverity = "critical" | "high" | "medium" | "low" | "info";

